-- 通过版SQL示例，用于验证整合流程
CREATE TABLE IF NOT EXISTS biz_table (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_name (name)
) ENGINE=InnoDB CHARSET=utf8mb4;

INSERT INTO biz_table (name) VALUES ('alice');
